#!/usr/bin/env bats
# ==============================================================================
# Test suite for scripts/doctor-hooks.sh
#
# doctor-hooks is READ-ONLY. These tests run it against an isolated fixture repo
# in BATS_TEST_TMPDIR: a git repo with .git/hooks populated by hand, a minimal
# .pre-commit-config.yaml, and a `pre-commit` PATH shim (mock_pre_commit) so the
# framework checks pass deterministically without the real tool or a network.
#
# The focus is the pre-push shim-identity check: the installed pre-push hook must
# carry pre-commit's generated-shim marker. The check keys on the marker TEXT,
# not a byte comparison, because the live shim's shebang embeds a machine-specific
# nix-store path. Fixtures cover the three outcomes: a marker-carrying shim
# (passes), a foreign hand-rolled file (warns, naming the dropped guard chain),
# and a missing file (the hook-installation loop's existing handling).
#
# Run with: bats tests/bats/doctor-hooks.bats
# ==============================================================================

setup() {
    source "$BATS_TEST_DIRNAME/common.sh"

    REPO_ROOT="$BATS_TEST_DIRNAME/../.."

    cd "$BATS_TEST_TMPDIR" || exit 1

    # Script + its sourced log library, mirroring the real scripts/ layout
    # (doctor-hooks.sh sources lib/log.sh relative to its own directory).
    mkdir -p scripts/lib
    cp "$REPO_ROOT/scripts/doctor-hooks.sh" scripts/
    cp "$REPO_ROOT/scripts/lib/log.sh" scripts/lib/

    # A real repo so .git/hooks exists; hooks are written by hand below.
    git init --initial-branch=main -q
    git config user.email "test@example.com"
    git config user.name "Test User"

    # Minimal config so Check 2 passes and the summary finds one repo entry.
    cat > .pre-commit-config.yaml <<'EOF'
repos:
  - repo: local
    hooks:
      - id: guard-main-push
        name: guard-direct-push-to-main
        entry: scripts/guard-main-push.sh
        language: script
        stages: [pre-push]
EOF

    # A `pre-commit` shim so Check 1 (version) and Check 6 (dry-run) pass without
    # the real framework — the suite's PATH-shim idiom (see mock_just/mock_gh).
    mock_pre_commit

    # The pre-commit and commit-msg stages are always installed as managed shims;
    # only the pre-push hook is varied per test, so a foreign/missing pre-push is
    # the sole difference driving the outcome under study.
    write_managed_shim .git/hooks/pre-commit
    write_managed_shim .git/hooks/commit-msg
}

teardown() {
    cd "$BATS_TEST_DIRNAME" || exit 1
}

# A `pre-commit` PATH shim: reports a version, answers --help, and treats `run`
# as a no-op success, so the framework checks are deterministic and offline.
mock_pre_commit() {
    mkdir -p "$BATS_TEST_TMPDIR/bin"
    cat > "$BATS_TEST_TMPDIR/bin/pre-commit" <<'EOF'
#!/bin/sh
case "${1:-}" in
    --version) echo "pre-commit 4.5.1" ;;
    --help)    : ;;
    run)       : ;;
    *)         : ;;
esac
exit 0
EOF
    chmod +x "$BATS_TEST_TMPDIR/bin/pre-commit"
    export PATH="$BATS_TEST_TMPDIR/bin:$PATH"
}

# Write an executable pre-commit-managed shim to $1. The marker sits on line 2,
# exactly as pre-commit generates it; the shebang carries a machine-specific
# nix-store path to prove the check keys on the marker text, not byte identity.
write_managed_shim() {
    cat > "$1" <<'EOF'
#!/nix/store/0000000000000000000000000000000-bash-5.3/bin/bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03
exec pre-commit hook-impl --config=.pre-commit-config.yaml -- "$@"
EOF
    chmod +x "$1"
}

# Write an executable hand-rolled pre-push hook with NO pre-commit marker.
write_foreign_hook() {
    cat > "$1" <<'EOF'
#!/bin/sh
# hand-rolled pre-push hook, not managed by pre-commit
echo "running custom pre-push checks"
EOF
    chmod +x "$1"
}

# ==============================================================================
# Managed shim -> passes, in the ok register
# ==============================================================================

@test "doctor-hooks: pre-push managed shim -> ok register, exit 0" {
    write_managed_shim .git/hooks/pre-push
    run sh scripts/doctor-hooks.sh
    echo "STATUS: $status" >&2; echo "OUTPUT: $output" >&2
    [ "$status" -eq 0 ]
    [[ "$output" == *"pre-push hook is the pre-commit-managed shim"* ]]
    # No foreign-file warning when the marker is present.
    [[ "$output" != *"is not the pre-commit-managed shim"* ]]
}

# ==============================================================================
# Foreign file -> warns loudly, names the dropped guards, non-fatal (exit 0)
# ==============================================================================

@test "doctor-hooks: foreign pre-push file -> warns, names dropped guards, exit 0" {
    write_foreign_hook .git/hooks/pre-push
    run sh scripts/doctor-hooks.sh
    echo "STATUS: $status" >&2; echo "OUTPUT: $output" >&2
    # Advisory: a foreign shim is a warning, not a gate failure.
    [ "$status" -eq 0 ]
    [[ "$output" == *"Warning:"* ]]
    [[ "$output" == *"is not the pre-commit-managed shim"* ]]
    # The message names the guard chain that pushing would now skip.
    [[ "$output" == *"guard-main-push"* ]]
    [[ "$output" == *"verify-rust"* ]]
}

# ==============================================================================
# Missing file -> the hook-installation loop's existing handling, no new finding
# ==============================================================================

@test "doctor-hooks: missing pre-push hook -> existing loop reports it, no shim warning" {
    rm -f .git/hooks/pre-push
    run sh scripts/doctor-hooks.sh
    echo "STATUS: $status" >&2; echo "OUTPUT: $output" >&2
    # The hook-installation loop already fails a missing stage -> exit 1.
    [ "$status" -eq 1 ]
    [[ "$output" == *"pre-push hook not installed"* ]]
    # The shim-identity check adds nothing for the missing case.
    [[ "$output" != *"is not the pre-commit-managed shim"* ]]
    [[ "$output" != *"pre-push hook is the pre-commit-managed shim"* ]]
}
